### ISSUE TITLE
The workings of the contentPane

### ISSUE THREAD

**Issue by pizzadox9999** [keinhaar/gwtswing#7]
Hi, I have a question about the workings of the content pane (most likely an error on my side ^^ but still). The problem is that when I set the background color or add an element to a GFrame or GDialog it happens within the top level element for the Frame or Dialog and not on the content pane. Do you have the same behaviour? If not I will look into how to properly access the first and last elements in their child list, because I think you just get the wrong child because of the trickery I went through. Besides that I have one div element which I don't now the purpose of or why it is created: `<div elementid="2" style="left: 0px; top: 50px; z-index: 10000;"></div>`. The elementid is from me. It indicates that it is the second element created from the TeavmGPDocument code. I would be curios about some insight from your end.

pizzadox9999

**Comment by keinhaar** [comment]
You are right and wrong with the contentpane at the same time :-). That's a Bug. I always use getContentPane().xxxx, so i did'nt notice. In Swing some methods of JFrame and JDialog are overridden to use the contentpane directly. This is at least true for all add(...) methods and setLayout(...), but it is not true for setBackground().
So i will fix this in the way it is done in swing.
That means, to set the Background of the GFrame you will still need to call gframe.getContentPane().setBackground(color), but you will be able to add Components just by calling gframe.add(component), and they will be added to the contentpane instead.
About the div element: This is an element called measueElement inside of gwtswing, and is created in GUtilities. It's used a lot in different classes to "measure" the preferredSize of components. You can just ignore it.

**Comment by pizzadox9999** [comment]
Thank you for the clarification and the "fix".

**Comment by keinhaar** [comment]
I've fixed it, and added nobuto as build system to gplatform, gplatform.gwt, gplatform.teavm and gwtswing.
So now you will only need to call 
```
sh nobuto.sh -t installToMaven
```
like shown on the README.md.
You should now definately update your projects, because i unified the groupId accross all subprojects.

Anyway, i tried to to run my demo app with teavm, but it does not work, because GPlatform.getWin().getClientWidth() does not return a valid size ("00000000"). Also GSwingUtilities.invokeLater() does not work, which depends on GPTimer. Any ideas on that?

**Comment by pizzadox9999** [comment]
Does nobuto work with teavm?
GPlatform.getWin().getClientWidth(): uses innerWidth from the window(it works for me so I thought it was fixed). GSwingUtilities.invokeLater(): it should be my thread implementation.But I have to look into it for certainty.
PS_0: I did a pull request for gplatform.teavm.
PS_1: Since the "fix" is in place I can't add things to the GFrame any more. I get a null exception.

**Comment by keinhaar** [comment]
For windows, there is nobuto.bat 😉
It's pure Java, so if you can call the teavm compiler from commandline, it should be easy by using the runCommand() method. Just look into build/Build.java.


Am 4. Juni 2023 15:55:35 MESZ schrieb pizzadox9999 ***@***.***>:

**Comment by pizzadox9999** [comment]
For the invoke later problem, I was able to run this code: 
`System.out.println("start: " + System.currentTimeMillis());
GSwingUtilities.invokeLater(new Runnable() {
    @Override
    public void run() {
        System.out.println("actual running time: " + System.currentTimeMillis());
    }
});
System.out.println("end: " + System.currentTimeMillis());`.

With the following results: 
start: 1685899608415
classes.js:26 end: 1685899608422
classes.js:26 actual running time: 1685899608438

**Comment by pizzadox9999** [comment]
For adding a component directly to a GFrame I experienced a failure on null. I tested it with a panel and a button. But if I add it to the content pane then it works. It may be because the add function is from the GComponent which uses it's internal list for the amount of elements which is in a GWindow already at two. Then the addImplemenation gets the index 2. So you have (I guess) an index out of bounds exception, because the contentpane has zero elements and you want to add it at index 2 instead of zero.

**Comment by keinhaar** [comment]
My bad. Did not really test it :-(
Fixed the GFrame error.
I will test the invokeLater again.

**Comment by keinhaar** [comment]
OK, I've managed to get my showcase running.
I've added the demo project as "gwtswing.showcase" to github.
In the teavm Client.java i have just
```java
public static void main(String[] args) 
{
    TeavmGPlatform.init();
    new SwingSet();
}
```
The Look is nearly exactly the same as in my gwt demo, and most things are working as expected. 
But Buttons seem to need 2 clicks to do anything. Same for menus. And the GList does not work.
Any ideas on that?

I needed to patch some stuff in gplatform.teavm to achieve this. Most interesting is the change of schedule in TeavmGPTimer. Instead of the Thread code i now use Window.setTimeout(). I've read that the Threading support in Teavm is some sort of green Threads, but GSwingUtilities.invokeLater() should run on the main thread, and that the way i do it in GWT.
Also i've added source Jars in installToMaven, to make debugging easier.
So you should update again.

**Comment by keinhaar** [comment]
And by the way, I've added the missing nobuto.jar files. They had been ignored because of the .gitignore file.

**Comment by pizzadox9999** [comment]
What I got for the button is the following. If I attach a GMouseAdapter to a component it is executed one time, when I click on the GComponent. But when I use a GButton it is executed two times (the mouse clicked function). Did you implement it like this. Is it with gwt the same? This behaviour for the GButton only occures if I do a short pressed (if I hold the mouse down for like more then have a second it is only executed ones). So all the classes extending the GButton suffer from this behaviour, but doesn't seem affected by pushing the mousebutton longer. I wrote a little test where the GMenu rejects executing the action performed method for a second time. With this the menu opens as it should. So I think it boils down to the GAbstractButton which executes the actionPerformed method on magical way two times instead of one. That's all I got for now. =)

**Comment by pizzadox9999** [comment]
Hi, I found the culprit. I didn't implemented the event attaching thing correct. With the commit "[fixed Gbutton pressed two times](https://github.com/keinhaar/gplatform.teavm/pull/5/commits/3e6fbb9681bbbb72afd752cc99f5dac954aaaa7e)" (should be in a pull request) should the bug be gone. But two known bugs still remain. 1. The gprogressbar doesn't have a background color. 2. The gsplitpane has an offset on the move thing.

**Comment by pizzadox9999** [comment]
So, the progessbar was more or less straight forward but the splitpane seems to be another beast. If I copy the example splitpane from the swingset and put it directly into a frame then it works as expected. But in the splitpane the action for the sliding is offset. To say at leat I'm impressed by such a bug.

**Comment by keinhaar** [comment]
I will have a look at the weekend.

Am 8. Juni 2023 16:25:34 MESZ schrieb pizzadox9999 ***@***.***>:

**Comment by pizzadox9999** [comment]
No rush

Am 9. Juni 2023 10:43:52 MESZ schrieb keinhaar ***@***.***>:

**Comment by keinhaar** [comment]
> So, the progessbar was more or less straight forward but the splitpane seems to be another beast. If I copy the example splitpane from the swingset and put it directly into a frame then it works as expected. But in the splitpane the action for the sliding is offset. To say at leat I'm impressed by such a bug.

Looks like there is a difference in GPElement.getAbsoluteLeft() between gwt and teavm. I think gwt may be wrong, but i'm afraid what happens if i change that. needs more investigation.

**Comment by pizzadox9999** [comment]
I looked into the implemenation. For that I copied the implemenation for getAbsoluteLeft/Top from the gwt's source code. There shouldn't be any discrepancy between them.

**Comment by keinhaar** [comment]
yes, i know you did, but you copied it from DomImpl, and there are several subclasses of DOMImpl for different Browsers. Chrome seems to use DOMImplStandardBase, which overrides getAbsolutLeft. DOMImplMozilla does also override the method, but in a different way. so i still believe that this is the reason for the offset. i will do more checks.

**Comment by keinhaar** [comment]
OK, i double checked with the Java Swing API, and the behaviour i see in the GWT implementation seems to be correct.
So i need to fix the teavm version.

**Comment by keinhaar** [comment]
Fixed the SplitPane by fixing the getAbsoluteLeft() method in TeavmGPElement. I've checked with Firefox and Chromium on Linux, but i'm pretty sure, this will work in any modern browser.
